# Generated by Django 5.1.3 on 2025-01-27 15:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("agent_id", models.CharField(max_length=32, unique=True)),
                ("agent_secret", models.CharField(max_length=64)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["agent_id"], name="telescope_s_agent_i_797a9a_idx"
                    ),
                    models.Index(fields=["name"], name="telescope_s_name_559c67_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("memory_total_kb", models.IntegerField(null=True)),
                ("memory_free_kb", models.IntegerField(null=True)),
                ("memory_used_kb", models.IntegerField(null=True)),
                ("memory_avail_kb", models.IntegerField(null=True)),
                (
                    "battery_charge",
                    models.DecimalField(decimal_places=3, max_digits=4, null=True),
                ),
                ("battery_standby", models.BooleanField(null=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="telescope.system",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.CharField(max_length=32)),
                ("agent_secret", models.CharField(max_length=64)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["agent_id"], name="telescope_s_agent_i_5c82bd_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("temp_c", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temps",
                        to="telescope.snapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZFSPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("size", models.CharField(max_length=32)),
                ("allocated", models.CharField(max_length=32)),
                ("free", models.CharField(max_length=32)),
                ("usage", models.DecimalField(decimal_places=3, max_digits=4)),
                ("health", models.CharField(max_length=32)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zfs_pools",
                        to="telescope.snapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("rpm", models.IntegerField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fans",
                        to="telescope.snapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["snapshot", "group", "name"],
                        name="telescope_f_snapsho_b02a2f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CPUCore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("usage", models.DecimalField(decimal_places=3, max_digits=4)),
                ("freq_mhz", models.IntegerField()),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpu_cores",
                        to="telescope.snapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["snapshot", "number"],
                        name="telescope_c_snapsho_1ccc10_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(max_length=128)),
                ("mountpoint", models.CharField(max_length=256)),
                ("filesystem", models.CharField(max_length=32)),
                ("total_kb", models.IntegerField()),
                ("free_kb", models.IntegerField()),
                ("used_kb", models.IntegerField()),
                ("utilization", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storages",
                        to="telescope.snapshot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["snapshot", "device"],
                        name="telescope_s_snapsho_14ea9c_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["timestamp"], name="telescope_s_timesta_4a31c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snapshot",
            index=models.Index(
                fields=["system", "timestamp"], name="telescope_s_system__dc5989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="temperature",
            index=models.Index(
                fields=["snapshot", "group", "name"],
                name="telescope_t_snapsho_d56131_idx",
            ),
        ),
    ]
