# Generated by Django 5.1.3 on 2025-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snapshot",
            name="load_long",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snapshot",
            name="load_med",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snapshot",
            name="load_short",
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
