# Generated by Django 5.1.3 on 2025-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telescope", "0002_snapshot_load_long_snapshot_load_med_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snapshot",
            name="load_long",
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="load_med",
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="load_short",
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
